### ISSUE TITLE
GridfinityBox Cannot use Lite with Scoop together.

### ISSUE THREAD

**Issue by Gray-Stone** [michaelgale/cq-gridfinity#10] opened 2024-07-26 05:08 UTC
When generating a GridfinityBox, The Scoop champer will disappear if Lite option is also selected.

Example code 
```
WALL_THICKNESS = 0.85
LABEL_OVERHANG_ANGLE =  math.radians(40)
LABEL_WIDTH = 10

bx = cqgf.GridfinityBox(
    1,1,7,
    lite_style=True,
    labels=True,
    label_width=LABEL_WIDTH,
    label_height =LABEL_WIDTH * math.tan(LABEL_OVERHANG_ANGLE),
    scoops = True ,
    scoop_rad = 5,
    wall_th = WALL_THICKNESS,
    fillet_interior = True,
)
```
Example output 
![image](https://github.com/user-attachments/assets/fd218cc8-fdab-4954-9080-8faba6fc08c7)

**Comment by michaelgale** [comment] 2024-07-26 19:12
This is intentional behaviour and not a bug.  The Lite style box is designed to consume minimal filament and decrease print time by eliminating the bottom floor including associated features such as the bottom scoop.  Furthermore, the Lite style does not typically need a scoop since its bottom wall profile is sloped rather than a sharp 90 corner.  In practice, a Lite style box offers satisfactory scoop-ability without requiring an additional scoop feature.

**Comment by michaelgale** [comment] 2024-07-26 19:23
However, I now do see a bug with how it renders the wall profile on the wall opposite the label wall.  I will have to fix that!

**Comment by michaelgale** [comment] 2024-07-26 19:57
I committed a fix which now checks for the incompatible selection of scoops and lite-style boxes.

**Comment by Gray-Stone** [comment] 2024-07-26 20:27
I personally have found the "Lite" btm is not enough of a scoop for fishing out part. I usually give a huge scoop radius like 15 for deep boxes. Is it possible to have the scoop btm with the Lite base? My view is the scoop btm is a must have feature for me, and having lite btm is basically saving material as much as I can everywhere else. So the two feature are independent from each other.
I was hopping for a combined feature like this from gridfinity-extended. Where scoop is applied after the lite operation.
![image](https://github.com/user-attachments/assets/2b06652c-0624-420a-aba0-830e029fcec0)

**Comment by michaelgale** [comment] 2024-07-29 16:19
Provisional support for scoops with lite style boxes has been added in the latest commit.  There are still some edge cases where this might not work, so I am not publishing a full release yet on pypi.  However, you can still test by using the latest version on the main branch.

**Comment by michaelgale** [comment] 2024-11-21 18:56
New version 0.5.7 adds the scoop feature to the lite style box.

**Closed by michaelgale** 2024-11-21 18:56 UTC
